export const INIT_DIRECTORY_TREE: string = "INIT_DIRECTORY_TREE";
export const INIT_DIRECTORY_TREE_SUCCESS: string =
  "INIT_DIRECTORY_TREE_SUCCESS";
export const INIT_DIRECTORY_TREE_FAILED: string = "INIT_DIRECTORY_TREE_FAILED";
export const LOAD_NEW_NODE = "LOAD_NEW_NODE";
export const LOAD_ALL_NEW_NODES = "LOAD_ALL_NEW_NODES";
export const LOAD_NEW_NODE_SUCCESS = "LOAD_NEW_SUCCESS";
export const LOAD_NEW_NODE_FAILED = "LOAD_NEW_FAILED";
export const LOAD_NEW_NODE_SUCCESS_WITHOUT_DATA =
  "LOAD_NEW_NODE_SUCCESS_WITHOUT_DATA";


export const LOAD_FILE = "LOAD_FILE";
export const LOAD_FILE_SUCCESS = "LOAD_FILE_SUCCESS";
export const LOAD_FILE_FAILED = "LOAD_FILE_FAILED";


export const CREATE_NEW_APP_INSTANCE = "CREATE_NEW_APP_INSTANCE";
export const DELETE_APP_INSTANCE = "DELETE_APP_INSTANCE";
export const SET_ACTIVE_APP_INSTANCE = "SET_ACTIVE_APP_INSTANCE";
export const CACHE_OPEN_NODES = "CACHE_OPEN_NODES";
export const SET_FILE_ACTIVE = "SET_FILE_ACTIVE";
export const OPEN_FILE = "OPEN_FILE";
export const CLOSE_FILE = "CLOSE_FILE";

export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";

